#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme

dir="$HOME/lu-dotfiles/.config/rofi/useful-stuff"
RASI="$dir/style-1.rasi"


# Run
rofi \
    -show run \
	-theme ${RASI}
