#!/usr/bin/env bash

# Import Current Theme

dir="$HOME/lu-dotfiles/.config/rofi/useful-stuff"
RASI="$dir/windows.rasi"

# Theme Elements
prompt='Useful Commands'
mesg="System tools"

# Options
layout=`cat ${RASI} | grep 'USE_ICON' | cut -d'=' -f2`
if [[ "$layout" == 'NO' ]]; then
	option_1="placeholder"
	option_2="placeholder"
	option_3="placeholder"
	option_4="placeholder"
	option_5="placeholder"
	option_6="placeholder"
	else
	option_1="󰑥  Reload Sway"	
	option_2="  Waybar Toggle"
	option_3="  JoyconD driver toggle"
	option_4="󰓓  Steam silent"
	option_5="  Font Manager"
	option_6="  NWG-Look"
	option_7="󰰊  Kivantum"
	option_8="  Azote"
	option_9="󱉬  GPaste"
	option_10="  Settings"
fi

# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-p "$prompt" \
		-mesg "$mesg" \
		-markup-rows \
		-theme ${RASI}
}

run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5\n$option_6\n$option_7\n$option_8\n$option_9\n$option_10" | rofi_cmd
}

# Execute Command
run_cmd() {
	if [[ "$1" == '--opt1' ]]; then
		swaymsg reload
	elif [[ "$1" == '--opt2' ]]; then
		sh ~/lu-dotfiles/components/toggles/waybar-toggle
	elif [[ "$1" == '--opt3' ]]; then
		sh ~/lu-dotfiles/components/toggles/joycond-toggle
	elif [[ "$1" == '--opt4' ]]; then
		steam -nochatui -nofriendsui -silent
	elif [[ "$1" == '--opt5' ]]; then
		font-manager
	elif [[ "$1" == '--opt6' ]]; then
		nwg-look
	elif [[ "$1" == '--opt7' ]]; then
		kvantummanager
	elif [[ "$1" == '--opt8' ]]; then
		azote
	elif [[ "$1" == '--opt9' ]]; then
		/usr/lib/gpaste/gpaste-ui
	elif [[ "$1" == '--opt10' ]]; then
		sh ~/lu-dotfiles/components/toggles/settings/sway-settings
	fi 
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
    $option_1)
		run_cmd --opt1
        ;;
    $option_2)
		run_cmd --opt2
        ;;
    $option_3)
		run_cmd --opt3
        ;;
    $option_4)
		run_cmd --opt4
        ;;
    $option_5)
		run_cmd --opt5
        ;;
	$option_6)
		run_cmd --opt6
        ;;   
	$option_7)
		run_cmd --opt7
        ;;    
	$option_8)
		run_cmd --opt8
        ;;    
	$option_9)
		run_cmd --opt9
        ;;    
	$option_10)
		run_cmd --opt10
        ;;

esac