#!/usr/bin/env bash

# Import Current Theme
DIR="$HOME/.config/sway/scripts/Rofi"
STYLE="default"
RASI="$DIR/Rasi/runner.rasi"

# Theme Elements
prompt='Useful Commands'
mesg="Crown, Joycond and MPD switches"

# Options
layout=`cat ${RASI} | grep 'USE_ICON' | cut -d'=' -f2`
if [[ "$layout" == 'NO' ]]; then
	option_1="placeholder"
	option_2="placeholder"
	option_3="placeholder"
	option_4="placeholder"
	option_5="placeholder"
	option_6="placeholder"
	else
	option_1="  Crown bot toggle"
	option_2="  JoyconD driver toggle"
	option_3="  Waybar Toggle"
	option_4="󰈣  Start Cmus"
	option_5="󰊴  Start Retro Arch"
	option_6="󰓓  steam -nochatui -nofriendsui -silent"
	option_7=""
	option_8="  Settings"
fi

# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-p "$prompt" \
		-mesg "$mesg" \
		-markup-rows \
		-theme ${RASI}
}

run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5\n$option_6" | rofi_cmd
}

# Execute Command
run_cmd() {
	if [[ "$1" == '--opt1' ]]; then
		sh ~/arch-config/sway/scripts/toggles/crown-toggle
	elif [[ "$1" == '--opt2' ]]; then
		sh ~/arch-config/sway/scripts/toggles/joycond-toggle
	elif [[ "$1" == '--opt3' ]]; then
		sh ~/arch-config/sway/scripts/toggles/waybar-toggle
	elif [[ "$1" == '--opt4' ]]; then
		kitty -e cmus
	elif [[ "$1" == '--opt5' ]]; then
		steam steam://rungameid/1118310
	elif [[ "$1" == '--opt6' ]]; then
		steam -nochatui -nofriendsui -silent
	elif [[ "$1" == '--opt7' ]]; then
		ls
	elif [[ "$1" == '--opt8' ]]; then
		sh ~/arch-config/sway/scripts/Rofi/Scripts/Settings/sway-settings
	fi
}
y

# Actions
chosen="$(run_rofi)"
case ${chosen} in
    $option_1)
		run_cmd --opt1
        ;;
    $option_2)
		run_cmd --opt2
        ;;
    $option_3)
		run_cmd --opt3
        ;;
    $option_4)
		run_cmd --opt4
        ;;
    $option_5)
		run_cmd --opt5
        ;;
	$option_6)
		run_cmd --opt6
        ;;   
	$option_7)
		run_cmd --opt7
        ;;    
	$option_8)
		run_cmd --opt8
        ;;

esac