version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 30m
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
      ND_ENABLESHARING: true
      ND_ENABLEREPLAYGAIN: true
    volumes:
      - "/home/luiza/bulkstorage/navidrome-data:/data"
      - "/home/luiza/bulkstorage/musica:/music:ro"
