#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme

dir="$HOME/lu-dotfiles/.config/rofi/useful-stuff"
RASI="$dir/windows.rasi"

# Theme Elements
current_workspace="`swaymsg -t get_tree | grep current_workspace`"
prompt="$current_workspace"
mesg="$current_workspace"

# Options
layout=`cat ${RASI} | grep 'USE_ICON' | cut -d'=' -f2`
if [[ "$layout" == 'NO' ]]; then
	option_1="Workspace 1"
	option_2="Workspace 2"
	option_3="Workspace 3"
	option_4="Workspace 4"
	option_5="Workspace 5"
	option_6="Workspace 6"
	option_7="Workspace 7"
	option_8="Workspace 8"
	option_9="Workspace 9"
	option_10="Workspace 10"
else
	option_1="Workspace 1"
	option_2="Workspace 2"
	option_3="Workspace 3"
	option_4="Workspace 4"
	option_5="Workspace 5"
	option_6="Workspace 6"
	option_7="Workspace 7"
	option_8="Workspace 8"
	option_9="Workspace 9"
	option_10="Workspace 10"
fi

# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-p "$prompt" \
		-mesg "$mesg" \
		-markup-rows \
		-theme ${RASI}
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5\n$option_6\n$option_7\n$option_8\n$option_9\n$option_10" | rofi_cmd
}

# Execute Command
run_cmd() {
	if [[ "$1" == '--opt1' ]]; then
		swaymsg workspace 1
	elif [[ "$1" == '--opt2' ]]; then
		swaymsg workspace 2
	elif [[ "$1" == '--opt3' ]]; then
		swaymsg workspace 3
	elif [[ "$1" == '--opt4' ]]; then
		swaymsg workspace 4
	elif [[ "$1" == '--opt5' ]]; then
		swaymsg workspace 5
	elif [[ "$1" == '--opt6' ]]; then
		swaymsg workspace 6
	elif [[ "$1" == '--opt7' ]]; then
		swaymsg workspace 7
	elif [[ "$1" == '--opt8' ]]; then
		swaymsg workspace 8
	elif [[ "$1" == '--opt9' ]]; then
		swaymsg workspace 9
	elif [[ "$1" == '--opt10' ]]; then
		swaymsg workspace 10
	fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
    $option_1)
		run_cmd --opt1
        ;;
    $option_2)
		run_cmd --opt2
        ;;
    $option_3)
		run_cmd --opt3
        ;;
    $option_4)
		run_cmd --opt4
        ;;
    $option_5)
		run_cmd --opt5
        ;;
    $option_6)
		run_cmd --opt6
        ;;
    $option_7)
		run_cmd --opt7
        ;;
    $option_8)
		run_cmd --opt8
        ;;
    $option_9)
		run_cmd --opt9
        ;;
    $option_10)
		run_cmd --opt10
        ;;
esac
